<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af9010a0d526571756573742e70726f746f120f6d6573736167652e7061" .
            "796c6f616422ce010a0752657175657374122f0a06686561646572180120" .
            "01280b321f2e6d6573736167652e7061796c6f61642e526571756573742e" .
            "486561646572120c0a04626f64791802200128091a83010a064865616465" .
            "72120f0a0773657276696365180120012809120e0a066d6574686f641802" .
            "20012809120e0a06646f6d61696e180320012809120f0a0776657273696f" .
            "6e180420012809120c0a0474797065180520012805120b0a036d49641806" .
            "20012809120b0a0375726c180720012809120f0a07746f6b656e49641808" .
            "20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

