<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto

namespace GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd010a0e526573706f6e73652e70726f746f120f6d6573736167652e70" .
            "61796c6f61642291010a08526573706f6e7365120c0a04626f6479180120" .
            "01280912300a0668656164657218022001280b32202e6d6573736167652e" .
            "7061796c6f61642e526573706f6e73652e4865616465721a450a06486561" .
            "646572120f0a076d657373616765180120012809120c0a04636f64651802" .
            "20012805120f0a0773756363657373180320012808120b0a036d49641804" .
            "20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

