<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ESearch.proto

namespace GPBMetadata;

class ESearch
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5020a0d455365617263682e70726f746f120b50726f746f6275662e45" .
            "5322590a0d5365617263685265717565737412160a0e7365617263684361" .
            "7465676f727918012001280912100a086b6579776f726473180220012809" .
            "120c0a0470616765180a2001280512100a087061676553697a65180b2001" .
            "280522b3010a0e536561726368526573706f6e7365120e0a067374617475" .
            "7318012001280512380a06726573756c7418022001280b32282e50726f74" .
            "6f6275662e45532e536561726368526573706f6e73652e53656172636852" .
            "6573756c74120c0a047061676518032001280512100a087061676553697a" .
            "65180420012805120d0a05746f74616c1805200128051a280a0c53656172" .
            "6368526573756c74120a0a026964180120012805120c0a04646174611802" .
            "20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

