<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Person.proto

namespace GPBMetadata;

class Person
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5020a0c506572736f6e2e70726f746f120f50726f746f6275662e576f" .
            "726b657222e3010a06506572736f6e120c0a046e616d6518012001280912" .
            "0a0a026964180220012805120d0a05656d61696c18032001280912330a06" .
            "70686f6e657318042003280b32232e50726f746f6275662e576f726b6572" .
            "2e506572736f6e2e50686f6e654e756d6265721a4e0a0b50686f6e654e75" .
            "6d626572120e0a066e756d626572180120012809122f0a04747970651802" .
            "2001280e32212e50726f746f6275662e576f726b65722e506572736f6e2e" .
            "50686f6e6554797065222b0a0950686f6e6554797065120a0a064d4f4249" .
            "4c45100012080a04484f4d45100112080a04574f524b100222360a0b4164" .
            "6472657373426f6f6b12270a0670656f706c6518012003280b32172e5072" .
            "6f746f6275662e576f726b65722e506572736f6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

