<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto

namespace GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abf010a0e526573706f6e73652e70726f746f12106d6573736167652e70" .
            "6c61796c6f61642292010a08526573706f6e7365120c0a04626f64791801" .
            "2001280912310a0668656164657218022001280b32212e6d657373616765" .
            "2e706c61796c6f61642e526573706f6e73652e4865616465721a450a0648" .
            "6561646572120f0a076d657373616765180120012809120c0a04636f6465" .
            "180220012805120f0a0773756363657373180320012808120b0a036d4964" .
            "180420012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

