<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace Message\Playload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>message.playload.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.message.playload.Request.Header header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>string body = 2;</code>
     */
    private $body = '';

    public function __construct() {
        \GPBMetadata\Request::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.message.playload.Request.Header header = 1;</code>
     * @return \Message\Playload\Request_Header
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.message.playload.Request.Header header = 1;</code>
     * @param \Message\Playload\Request_Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Message\Playload\Request_Header::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

}

