<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ESearch.proto

namespace Protobuf\ES;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Protobuf.ES.SearchResponse</code>
 */
class SearchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>.Protobuf.ES.SearchResponse.SearchResult result = 2;</code>
     */
    private $result = null;
    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     */
    private $page = 0;
    /**
     * Generated from protobuf field <code>int32 pageSize = 4;</code>
     */
    private $pageSize = 0;
    /**
     * Generated from protobuf field <code>int32 total = 5;</code>
     */
    private $total = 0;

    public function __construct() {
        \GPBMetadata\ESearch::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Protobuf.ES.SearchResponse.SearchResult result = 2;</code>
     * @return \Protobuf\ES\SearchResponse_SearchResult
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.Protobuf.ES.SearchResponse.SearchResult result = 2;</code>
     * @param \Protobuf\ES\SearchResponse_SearchResult $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Protobuf\ES\SearchResponse_SearchResult::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pageSize = 4;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->pageSize;
    }

    /**
     * Generated from protobuf field <code>int32 pageSize = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->pageSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total = 5;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int32 total = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

}

