<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afb010a0d526571756573742e70726f746f12106d6573736167652e706c" .
            "61796c6f616422cf010a075265717565737412300a066865616465721801" .
            "2001280b32202e6d6573736167652e706c61796c6f61642e526571756573" .
            "742e486561646572120c0a04626f64791802200128091a83010a06486561" .
            "646572120f0a0773657276696365180120012809120e0a066d6574686f64" .
            "180220012809120e0a06646f6d61696e180320012809120f0a0776657273" .
            "696f6e180420012809120c0a0474797065180520012805120b0a036d4964" .
            "180620012809120b0a0375726c180720012809120f0a07746f6b656e4964" .
            "180820012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

