<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Person.proto

namespace Protobuf\Worker;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Our address book file is just one of these.
 *
 * Generated from protobuf message <code>Protobuf.Worker.AddressBook</code>
 */
class AddressBook extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Protobuf.Worker.Person people = 1;</code>
     */
    private $people;

    public function __construct() {
        \GPBMetadata\Person::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .Protobuf.Worker.Person people = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPeople()
    {
        return $this->people;
    }

    /**
     * Generated from protobuf field <code>repeated .Protobuf.Worker.Person people = 1;</code>
     * @param \Protobuf\Worker\Person[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPeople($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protobuf\Worker\Person::class);
        $this->people = $arr;

        return $this;
    }

}

